### ISSUE TITLE
'List' is not defined error when using arrays

### ISSUE THREAD

**Issue by avigadmi** [IBMStreams/pypi.streamsx.wml#4]
toolkit released 0.1.9

mapping dict: 
`"model_field":"__array__","tuple_field":"data" 
`

getting the following error:
Traceback (most recent call last):
  File "/opt/ibm/streams-ext/conda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/ibm/streams-ext/conda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/streamsapp/198510a4ead6934c76a6172d9b7dc77d11d9b966c0c6ed9a1e9ee568/output/toolkits/com.ibm.streams.wml/opt/python/streams/bundleresthandler/bundleresthandler.py", line 114, in run
    self.preprocess()
  File "/home/streamsapp/198510a4ead6934c76a6172d9b7dc77d11d9b966c0c6ed9a1e9ee568/output/toolkits/com.ibm.streams.wml/opt/python/streams/bundleresthandler/wmlbundleresthandler.py", line 97, in preprocess
    elif isinstance(tuple_field_value, List)  and len(self.field_mapping) is 1:
NameError: name 'List' is not defined

**Comment by estherhi** [comment]
Stressing this is a blocker for streams flows

**Comment by rnostream** [comment]
Is corrected in v1.0.0.
Added test case for list() input additional to existing test case for numpy.ndarray
